# Generated by Django 4.2.2 on 2023-06-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='budget.budget'),
        ),
    ]
