# Generated by Django 4.2.2 on 2023-06-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ONLINE_SHOPPING', 'Online'), ('CLOTHING', 'Clothing'), ('TOYS', 'Toys'), ('SYSTEM', 'System Bolaget'), ('CONVENIENCE', 'Convenience'), ('VOLVO', 'Volvo'), ('TRAVEL', 'Travel'), ('TAKEOUT', 'Takeout'), ('RENT', 'Rent'), ('ENTERTAINMENT', 'Entertainment'), ('BILLS', 'Bills'), ('CHARITY', 'Charity'), ('Recurring', 'Recurring'), ('OTHER', 'Other')], max_length=255),
        ),
    ]
