# Generated by Django 4.2.2 on 2023-06-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_remove_receipt_base_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.CharField(choices=[('INCOME', 'Income'), ('REFUND', 'Refund'), ('GIFT', 'Gift'), ('REBATE', 'Rebate'), ('OTHER', 'Other')], max_length=255),
        ),
    ]
