# Generated by Django 4.2.2 on 2023-06-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='budget_account', to='budget.budget'),
        ),
    ]
